### PR TITLE
support additional ca certs

### PR DESCRIPTION
**Pull request by gitlawr**
For issue: https://github.com/rancher/rancher/issues/16136

### CODE REVIEW

**Comment by cjellick** [comment]
Have we always had this repo forked? Do we have other custom commits on our fork? I dont see them at the top of this history.

**Comment by cjellick** [comment]
How do we release this image? who typically does that?

**Comment by loganhz** [comment]
@cjellick We used another solution https://github.com/rancher/rancher/issues/16136 to address this issue.
@gitlawr Please close this PR

**Comment by gitlawr** [comment]
Deprecated

**Pull request closed without merging**
